# course/ex15-sqldb/Dockerfile.ex15.1
FROM python:3.9.7                                          # changed!

WORKDIR /app 
RUN     apt update && \                                    # changed!
        apt install default-libmysqlclient-dev python-dev  # new!

ENV     DEBUG=True  \
        DATABASE_URL=sqlite:///db.sqlite3 \
        ADMIN_USER=admin  \
        ADMIN_EMAIL=admin@example.com  \
        ADMIN_PW='S4cret!'

VOLUME  /data
COPY    *  ./

RUN python3.9 -m pip install -r requirements.txt && \      # changed!
    python3.9 -m pip install mysqlclient                   # new!
RUN python3.9 manage.py migrate
CMD [ "/bin/sh", "/app/entrypoint.sh" ]
