# course/ex15-sqldb/Dockerfile.ex15.1
FROM python:3.9.7

WORKDIR /app

ENV     DEBUG=True  \
        DEBIAN_FRONTEND=noninteractive  \
        DATABASE_URL=sqlite:///db.sqlite3 \
        ADMIN_USER=admin  \
        ADMIN_EMAIL=admin@example.com  \
        ADMIN_PW='S4cret!'

RUN     apt update && \
        apt install -y default-libmysqlclient-dev python-dev

VOLUME  /data
COPY    *  ./

RUN python3.9 -m pip install -r requirements.txt  && \
    python3.9 -m pip install mysqlclient
RUN python3.9 manage.py migrate
CMD [ "/bin/sh", "/app/entrypoint.sh" ]
