#!/bin/bash
# course/ex11-compose/install-docker-compose"

export DIR=/usr/local/libexec/docker/cli-plugins
export URL="https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-linux-x86_64"

echo "#-- Create installation directory: $DIR"
mkdir -p $DIR
echo "#-- Download docker-compose binary : $URL"
wget $URL -O $DIR/docker-compose
chmod +x $DIR/docker-compose
