# course/ex08-app-newspaper/Dockerfile.ex09.4
FROM python:3.9.7-alpine3.14

WORKDIR /app
RUN     apk update

ENV     DEBUG=True \
        DATABASE_URL=sqlite:///db.sqlite3

VOLUME  /data
COPY    app/    .
COPY    entrypoint.sh   .

RUN python3.9 -m pip install -r requirements.txt
RUN python3.9 manage.py migrate
CMD [ "/bin/sh", "entrypoint.sh" ]
