# course/ex08-app-newspaper/Dockerfile.4
FROM python:3.9.7-alpine3.14

WORKDIR /app
RUN     apk update

ENV     DEBUG=True \
        DATABASE_URL=sqlite:///db.sqlite3

VOLUME  /data
COPY    app/    .

RUN python3.9 -m pip install -r requirements.txt
RUN python3.9 manage.py migrate
RUN sed -i '/ALLOWED_HOSTS/s/^.*$/ALLOWED_HOSTS=["*"]/g' django_project/settings.py
CMD ["python3.9", "manage.py", "runserver", "0.0.0.0:8000"]
