# Uncomment the lines below as instructed in the exercise

### The base image for this container:
### See: https://docs.docker.com/engine/reference/builder/#from
# FROM python:3-alpine

### Execute this command (or commands!) **inside** the container
### "RUN" is the primary tool to change the image's content
### See: https://docs.docker.com/engine/reference/builder/#run
# RUN apk update && apk add py3-django

### Make /app the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
### instructions that follow
### See: https://docs.docker.com/engine/reference/builder/#workdir
# WORKDIR /app

### Sets the default (but overrideable!) command that Docker will 
### execute as PID 1
### See: https://docs.docker.com/engine/reference/builder/#cmd
# CMD ["python3"]


